
package com.amadeus.xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.amadeus.xml.acsfrq_16_1_1a.DCSLSTGetCheckInSummaryFigures;
import com.amadeus.xml.acsfrr_16_1_1a.DCSLSTGetCheckInSummaryFiguresReply;
import com.amadeus.xml.apalrq_17_1_1a.DCSLSTGetPassengerList;
import com.amadeus.xml.apalrr_17_1_1a.DCSLSTGetPassengerListReply;
import com.amadeus.xml.vlssoq_04_1_1a.SecuritySignOut;
import com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AmadeusWebServicesPT", targetNamespace = "http://xml.amadeus.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.amadeus.xml.cfldrr_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.cfldrr_16_1_1a.ObjectFactory.class,
    com.amadeus.xml.acsfrr_16_1_1a.ObjectFactory.class,
    com.amadeus.xml.apalrq_17_1_1a.ObjectFactory.class,
    com.amadeus.xml.apalrr_17_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssoq_04_1_1a.ObjectFactory.class,
    com.amadeus.xml.vlssor_04_1_1a.ObjectFactory.class,
    com.amadeus.xml._2010._06.security_v1.ObjectFactory.class,
    org.iata.iata._2007._00.iata2010.ObjectFactory.class,
    org.opentravel.ota._2003._05.ota2010b.ObjectFactory.class,
    com.amadeus.xml._2010._06.types_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.appmdw_commontypes_v3.ObjectFactory.class,
    com.amadeus.wsdl._2010._06.ws.link_v1.ObjectFactory.class,
    com.amadeus.xml._2010._06.session_v3.ObjectFactory.class,
    com.amadeus.xml.acsfrq_16_1_1a.ObjectFactory.class,
    com.amadeus.xml.cfldrq_15_1_1a.ObjectFactory.class,
    com.amadeus.xml.cfldrq_16_1_1a.ObjectFactory.class
})
public interface AmadeusWebServicesPT {


    /**
     * 
     * @param dcslstFlightListDisplay151
     * @return
     *     returns com.amadeus.xml.cfldrr_15_1_1a.DCSLSTFlightListDisplayReply
     */
    @WebMethod(operationName = "DCSLST_FlightListDisplay_15_1", action = "http://webservices.amadeus.com/CFLDRQ_15_1_1A")
    @WebResult(name = "DCSLST_FlightListDisplayReply", targetNamespace = "http://xml.amadeus.com/CFLDRR_15_1_1A", partName = "DCSLST_FlightListDisplayReply_15_1")
    public com.amadeus.xml.cfldrr_15_1_1a.DCSLSTFlightListDisplayReply dcslstFlightListDisplay151(
        @WebParam(name = "DCSLST_FlightListDisplay", targetNamespace = "http://xml.amadeus.com/CFLDRQ_15_1_1A", partName = "DCSLST_FlightListDisplay_15_1")
        com.amadeus.xml.cfldrq_15_1_1a.DCSLSTFlightListDisplay dcslstFlightListDisplay151);

    /**
     * 
     * @param dcslstFlightListDisplay161
     * @return
     *     returns com.amadeus.xml.cfldrr_16_1_1a.DCSLSTFlightListDisplayReply
     */
    @WebMethod(operationName = "DCSLST_FlightListDisplay_16_1", action = "http://webservices.amadeus.com/CFLDRQ_16_1_1A")
    @WebResult(name = "DCSLST_FlightListDisplayReply", targetNamespace = "http://xml.amadeus.com/CFLDRR_16_1_1A", partName = "DCSLST_FlightListDisplayReply_16_1")
    public com.amadeus.xml.cfldrr_16_1_1a.DCSLSTFlightListDisplayReply dcslstFlightListDisplay161(
        @WebParam(name = "DCSLST_FlightListDisplay", targetNamespace = "http://xml.amadeus.com/CFLDRQ_16_1_1A", partName = "DCSLST_FlightListDisplay_16_1")
        com.amadeus.xml.cfldrq_16_1_1a.DCSLSTFlightListDisplay dcslstFlightListDisplay161);

    /**
     * 
     * @param dcslstGetCheckInSummaryFigures161
     * @return
     *     returns com.amadeus.xml.acsfrr_16_1_1a.DCSLSTGetCheckInSummaryFiguresReply
     */
    @WebMethod(operationName = "DCSLST_GetCheckInSummaryFigures", action = "http://webservices.amadeus.com/ACSFRQ_16_1_1A")
    @WebResult(name = "DCSLST_GetCheckInSummaryFiguresReply", targetNamespace = "http://xml.amadeus.com/ACSFRR_16_1_1A", partName = "DCSLST_GetCheckInSummaryFiguresReply_16_1")
    public DCSLSTGetCheckInSummaryFiguresReply dcslstGetCheckInSummaryFigures(
        @WebParam(name = "DCSLST_GetCheckInSummaryFigures", targetNamespace = "http://xml.amadeus.com/ACSFRQ_16_1_1A", partName = "DCSLST_GetCheckInSummaryFigures_16_1")
        DCSLSTGetCheckInSummaryFigures dcslstGetCheckInSummaryFigures161);

    /**
     * 
     * @param dcslstGetPassengerList171
     * @return
     *     returns com.amadeus.xml.apalrr_17_1_1a.DCSLSTGetPassengerListReply
     */
    @WebMethod(operationName = "DCSLST_GetPassengerList", action = "http://webservices.amadeus.com/APALRQ_17_1_1A")
    @WebResult(name = "DCSLST_GetPassengerListReply", targetNamespace = "http://xml.amadeus.com/APALRR_17_1_1A", partName = "DCSLST_GetPassengerListReply_17_1")
    public DCSLSTGetPassengerListReply dcslstGetPassengerList(
        @WebParam(name = "DCSLST_GetPassengerList", targetNamespace = "http://xml.amadeus.com/APALRQ_17_1_1A", partName = "DCSLST_GetPassengerList_17_1")
        DCSLSTGetPassengerList dcslstGetPassengerList171);

    /**
     * 
     * @param securitySignOut41
     * @return
     *     returns com.amadeus.xml.vlssor_04_1_1a.SecuritySignOutReply
     */
    @WebMethod(operationName = "Security_SignOut", action = "http://webservices.amadeus.com/VLSSOQ_04_1_1A")
    @WebResult(name = "Security_SignOutReply", targetNamespace = "http://xml.amadeus.com/VLSSOR_04_1_1A", partName = "Security_SignOutReply_4_1")
    public SecuritySignOutReply securitySignOut(
        @WebParam(name = "Security_SignOut", targetNamespace = "http://xml.amadeus.com/VLSSOQ_04_1_1A", partName = "Security_SignOut_4_1")
        SecuritySignOut securitySignOut41);

}
