//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 12:43:24 PM IST 
//


package com.ibsplc.oag.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cbwsPublicRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cbwsPublicRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atcPercentageRouting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bothWays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carrier1Criteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carrier2Criteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carrier3Criteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destinationCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destinationCriteriaLocationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enableOnline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="interAirportConnections" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logicalPathOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lowCostConnectionsIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxCT1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxCT2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxCircuity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxDoublesRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxElapsedTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxSinglesRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originCriteriaLocationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="overrideMinCT1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="overrideMinCT2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestDateEffectiveFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestDateEffectiveTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rtnRequestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rtnRequestTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="useForwardRoutes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="via1Criteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="via1CriteriaLocationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="via2Criteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="via2CriteriaLocationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preferredCarrierCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="excludeCarrierCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowRestrictedFlights" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestDateIsArriveBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cbwsPublicRequest", propOrder = {
    "atcPercentageRouting",
    "bothWays",
    "carrier1Criteria",
    "carrier2Criteria",
    "carrier3Criteria",
    "destinationCriteria",
    "destinationCriteriaLocationType",
    "enableOnline",
    "interAirportConnections",
    "logicalPathOnly",
    "lowCostConnectionsIndicator",
    "maxCT1",
    "maxCT2",
    "maxCircuity",
    "maxDoublesRoute",
    "maxElapsedTime",
    "maxSinglesRoute",
    "originCriteria",
    "originCriteriaLocationType",
    "overrideMinCT1",
    "overrideMinCT2",
    "password",
    "requestDate",
    "requestDateEffectiveFrom",
    "requestDateEffectiveTo",
    "requestTime",
    "rtnRequestDate",
    "rtnRequestTime",
    "sortOrder",
    "useForwardRoutes",
    "username",
    "via1Criteria",
    "via1CriteriaLocationType",
    "via2Criteria",
    "via2CriteriaLocationType",
    "preferredCarrierCriteria",
    "excludeCarrierCriteria",
    "allowRestrictedFlights",
    "requestDateIsArriveBy"
})
@XmlSeeAlso({
    CbwsPublicFlightLookupRequest.class
})
public class CbwsPublicRequest {

    protected String atcPercentageRouting;
    protected String bothWays;
    protected String carrier1Criteria;
    protected String carrier2Criteria;
    protected String carrier3Criteria;
    protected String destinationCriteria;
    protected String destinationCriteriaLocationType;
    protected String enableOnline;
    protected String interAirportConnections;
    protected String logicalPathOnly;
    protected String lowCostConnectionsIndicator;
    protected String maxCT1;
    protected String maxCT2;
    protected String maxCircuity;
    protected String maxDoublesRoute;
    protected String maxElapsedTime;
    protected String maxSinglesRoute;
    protected String originCriteria;
    protected String originCriteriaLocationType;
    protected String overrideMinCT1;
    protected String overrideMinCT2;
    protected String password;
    protected String requestDate;
    protected String requestDateEffectiveFrom;
    protected String requestDateEffectiveTo;
    protected String requestTime;
    protected String rtnRequestDate;
    protected String rtnRequestTime;
    protected String sortOrder;
    protected String useForwardRoutes;
    protected String username;
    protected String via1Criteria;
    protected String via1CriteriaLocationType;
    protected String via2Criteria;
    protected String via2CriteriaLocationType;
    protected String preferredCarrierCriteria;
    protected String excludeCarrierCriteria;
    protected String allowRestrictedFlights;
    protected String requestDateIsArriveBy;

    /**
     * Gets the value of the atcPercentageRouting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtcPercentageRouting() {
        return atcPercentageRouting;
    }

    /**
     * Sets the value of the atcPercentageRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtcPercentageRouting(String value) {
        this.atcPercentageRouting = value;
    }

    /**
     * Gets the value of the bothWays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBothWays() {
        return bothWays;
    }

    /**
     * Sets the value of the bothWays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBothWays(String value) {
        this.bothWays = value;
    }

    /**
     * Gets the value of the carrier1Criteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier1Criteria() {
        return carrier1Criteria;
    }

    /**
     * Sets the value of the carrier1Criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier1Criteria(String value) {
        this.carrier1Criteria = value;
    }

    /**
     * Gets the value of the carrier2Criteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier2Criteria() {
        return carrier2Criteria;
    }

    /**
     * Sets the value of the carrier2Criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier2Criteria(String value) {
        this.carrier2Criteria = value;
    }

    /**
     * Gets the value of the carrier3Criteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier3Criteria() {
        return carrier3Criteria;
    }

    /**
     * Sets the value of the carrier3Criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier3Criteria(String value) {
        this.carrier3Criteria = value;
    }

    /**
     * Gets the value of the destinationCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCriteria() {
        return destinationCriteria;
    }

    /**
     * Sets the value of the destinationCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCriteria(String value) {
        this.destinationCriteria = value;
    }

    /**
     * Gets the value of the destinationCriteriaLocationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCriteriaLocationType() {
        return destinationCriteriaLocationType;
    }

    /**
     * Sets the value of the destinationCriteriaLocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCriteriaLocationType(String value) {
        this.destinationCriteriaLocationType = value;
    }

    /**
     * Gets the value of the enableOnline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableOnline() {
        return enableOnline;
    }

    /**
     * Sets the value of the enableOnline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableOnline(String value) {
        this.enableOnline = value;
    }

    /**
     * Gets the value of the interAirportConnections property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterAirportConnections() {
        return interAirportConnections;
    }

    /**
     * Sets the value of the interAirportConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterAirportConnections(String value) {
        this.interAirportConnections = value;
    }

    /**
     * Gets the value of the logicalPathOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalPathOnly() {
        return logicalPathOnly;
    }

    /**
     * Sets the value of the logicalPathOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalPathOnly(String value) {
        this.logicalPathOnly = value;
    }

    /**
     * Gets the value of the lowCostConnectionsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowCostConnectionsIndicator() {
        return lowCostConnectionsIndicator;
    }

    /**
     * Sets the value of the lowCostConnectionsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowCostConnectionsIndicator(String value) {
        this.lowCostConnectionsIndicator = value;
    }

    /**
     * Gets the value of the maxCT1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxCT1() {
        return maxCT1;
    }

    /**
     * Sets the value of the maxCT1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxCT1(String value) {
        this.maxCT1 = value;
    }

    /**
     * Gets the value of the maxCT2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxCT2() {
        return maxCT2;
    }

    /**
     * Sets the value of the maxCT2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxCT2(String value) {
        this.maxCT2 = value;
    }

    /**
     * Gets the value of the maxCircuity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxCircuity() {
        return maxCircuity;
    }

    /**
     * Sets the value of the maxCircuity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxCircuity(String value) {
        this.maxCircuity = value;
    }

    /**
     * Gets the value of the maxDoublesRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDoublesRoute() {
        return maxDoublesRoute;
    }

    /**
     * Sets the value of the maxDoublesRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDoublesRoute(String value) {
        this.maxDoublesRoute = value;
    }

    /**
     * Gets the value of the maxElapsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxElapsedTime() {
        return maxElapsedTime;
    }

    /**
     * Sets the value of the maxElapsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxElapsedTime(String value) {
        this.maxElapsedTime = value;
    }

    /**
     * Gets the value of the maxSinglesRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxSinglesRoute() {
        return maxSinglesRoute;
    }

    /**
     * Sets the value of the maxSinglesRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxSinglesRoute(String value) {
        this.maxSinglesRoute = value;
    }

    /**
     * Gets the value of the originCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCriteria() {
        return originCriteria;
    }

    /**
     * Sets the value of the originCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCriteria(String value) {
        this.originCriteria = value;
    }

    /**
     * Gets the value of the originCriteriaLocationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCriteriaLocationType() {
        return originCriteriaLocationType;
    }

    /**
     * Sets the value of the originCriteriaLocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCriteriaLocationType(String value) {
        this.originCriteriaLocationType = value;
    }

    /**
     * Gets the value of the overrideMinCT1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideMinCT1() {
        return overrideMinCT1;
    }

    /**
     * Sets the value of the overrideMinCT1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideMinCT1(String value) {
        this.overrideMinCT1 = value;
    }

    /**
     * Gets the value of the overrideMinCT2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideMinCT2() {
        return overrideMinCT2;
    }

    /**
     * Sets the value of the overrideMinCT2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideMinCT2(String value) {
        this.overrideMinCT2 = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDate(String value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the requestDateEffectiveFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDateEffectiveFrom() {
        return requestDateEffectiveFrom;
    }

    /**
     * Sets the value of the requestDateEffectiveFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDateEffectiveFrom(String value) {
        this.requestDateEffectiveFrom = value;
    }

    /**
     * Gets the value of the requestDateEffectiveTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDateEffectiveTo() {
        return requestDateEffectiveTo;
    }

    /**
     * Sets the value of the requestDateEffectiveTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDateEffectiveTo(String value) {
        this.requestDateEffectiveTo = value;
    }

    /**
     * Gets the value of the requestTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestTime() {
        return requestTime;
    }

    /**
     * Sets the value of the requestTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestTime(String value) {
        this.requestTime = value;
    }

    /**
     * Gets the value of the rtnRequestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtnRequestDate() {
        return rtnRequestDate;
    }

    /**
     * Sets the value of the rtnRequestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtnRequestDate(String value) {
        this.rtnRequestDate = value;
    }

    /**
     * Gets the value of the rtnRequestTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtnRequestTime() {
        return rtnRequestTime;
    }

    /**
     * Sets the value of the rtnRequestTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtnRequestTime(String value) {
        this.rtnRequestTime = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortOrder(String value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the useForwardRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseForwardRoutes() {
        return useForwardRoutes;
    }

    /**
     * Sets the value of the useForwardRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseForwardRoutes(String value) {
        this.useForwardRoutes = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the via1Criteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia1Criteria() {
        return via1Criteria;
    }

    /**
     * Sets the value of the via1Criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia1Criteria(String value) {
        this.via1Criteria = value;
    }

    /**
     * Gets the value of the via1CriteriaLocationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia1CriteriaLocationType() {
        return via1CriteriaLocationType;
    }

    /**
     * Sets the value of the via1CriteriaLocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia1CriteriaLocationType(String value) {
        this.via1CriteriaLocationType = value;
    }

    /**
     * Gets the value of the via2Criteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia2Criteria() {
        return via2Criteria;
    }

    /**
     * Sets the value of the via2Criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia2Criteria(String value) {
        this.via2Criteria = value;
    }

    /**
     * Gets the value of the via2CriteriaLocationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia2CriteriaLocationType() {
        return via2CriteriaLocationType;
    }

    /**
     * Sets the value of the via2CriteriaLocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia2CriteriaLocationType(String value) {
        this.via2CriteriaLocationType = value;
    }

    /**
     * Gets the value of the preferredCarrierCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredCarrierCriteria() {
        return preferredCarrierCriteria;
    }

    /**
     * Sets the value of the preferredCarrierCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredCarrierCriteria(String value) {
        this.preferredCarrierCriteria = value;
    }

    /**
     * Gets the value of the excludeCarrierCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludeCarrierCriteria() {
        return excludeCarrierCriteria;
    }

    /**
     * Sets the value of the excludeCarrierCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludeCarrierCriteria(String value) {
        this.excludeCarrierCriteria = value;
    }

    /**
     * Gets the value of the allowRestrictedFlights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowRestrictedFlights() {
        return allowRestrictedFlights;
    }

    /**
     * Sets the value of the allowRestrictedFlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowRestrictedFlights(String value) {
        this.allowRestrictedFlights = value;
    }

    /**
     * Gets the value of the requestDateIsArriveBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDateIsArriveBy() {
        return requestDateIsArriveBy;
    }

    /**
     * Sets the value of the requestDateIsArriveBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDateIsArriveBy(String value) {
        this.requestDateIsArriveBy = value;
    }

}
