//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 12:43:24 PM IST 
//


package com.ibsplc.oag.vo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibsplc.oag.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetConnections_QNAME = new QName("http://ws.connections.oag.com/", "getConnections");
    private final static QName _GetDirectFlightsResponse_QNAME = new QName("http://ws.connections.oag.com/", "getDirectFlightsResponse");
    private final static QName _FlightLookupResponse_QNAME = new QName("http://ws.connections.oag.com/", "flightLookupResponse");
    private final static QName _GetConnectionsResponse_QNAME = new QName("http://ws.connections.oag.com/", "getConnectionsResponse");
    private final static QName _GetDirectFlights_QNAME = new QName("http://ws.connections.oag.com/", "getDirectFlights");
    private final static QName _CBWSPublicUnauthorizedAccessException_QNAME = new QName("http://ws.connections.oag.com/", "CBWSPublicUnauthorizedAccessException");
    private final static QName _FlightLookup_QNAME = new QName("http://ws.connections.oag.com/", "flightLookup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibsplc.oag.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightLookup }
     * 
     */
    public FlightLookup createFlightLookup() {
        return new FlightLookup();
    }

    /**
     * Create an instance of {@link CBWSPublicUnauthorizedAccessException }
     * 
     */
    public CBWSPublicUnauthorizedAccessException createCBWSPublicUnauthorizedAccessException() {
        return new CBWSPublicUnauthorizedAccessException();
    }

    /**
     * Create an instance of {@link GetDirectFlights }
     * 
     */
    public GetDirectFlights createGetDirectFlights() {
        return new GetDirectFlights();
    }

    /**
     * Create an instance of {@link GetConnectionsResponse }
     * 
     */
    public GetConnectionsResponse createGetConnectionsResponse() {
        return new GetConnectionsResponse();
    }

    /**
     * Create an instance of {@link FlightLookupResponse }
     * 
     */
    public FlightLookupResponse createFlightLookupResponse() {
        return new FlightLookupResponse();
    }

    /**
     * Create an instance of {@link GetConnections }
     * 
     */
    public GetConnections createGetConnections() {
        return new GetConnections();
    }

    /**
     * Create an instance of {@link GetDirectFlightsResponse }
     * 
     */
    public GetDirectFlightsResponse createGetDirectFlightsResponse() {
        return new GetDirectFlightsResponse();
    }

    /**
     * Create an instance of {@link CbwsPublicResponse }
     * 
     */
    public CbwsPublicResponse createCbwsPublicResponse() {
        return new CbwsPublicResponse();
    }

    /**
     * Create an instance of {@link CbwsPublicRequest }
     * 
     */
    public CbwsPublicRequest createCbwsPublicRequest() {
        return new CbwsPublicRequest();
    }

    /**
     * Create an instance of {@link CbwsPublicFlightLookupRequest }
     * 
     */
    public CbwsPublicFlightLookupRequest createCbwsPublicFlightLookupRequest() {
        return new CbwsPublicFlightLookupRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConnections }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "getConnections")
    public JAXBElement<GetConnections> createGetConnections(GetConnections value) {
        return new JAXBElement<GetConnections>(_GetConnections_QNAME, GetConnections.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDirectFlightsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "getDirectFlightsResponse")
    public JAXBElement<GetDirectFlightsResponse> createGetDirectFlightsResponse(GetDirectFlightsResponse value) {
        return new JAXBElement<GetDirectFlightsResponse>(_GetDirectFlightsResponse_QNAME, GetDirectFlightsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLookupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "flightLookupResponse")
    public JAXBElement<FlightLookupResponse> createFlightLookupResponse(FlightLookupResponse value) {
        return new JAXBElement<FlightLookupResponse>(_FlightLookupResponse_QNAME, FlightLookupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConnectionsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "getConnectionsResponse")
    public JAXBElement<GetConnectionsResponse> createGetConnectionsResponse(GetConnectionsResponse value) {
        return new JAXBElement<GetConnectionsResponse>(_GetConnectionsResponse_QNAME, GetConnectionsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDirectFlights }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "getDirectFlights")
    public JAXBElement<GetDirectFlights> createGetDirectFlights(GetDirectFlights value) {
        return new JAXBElement<GetDirectFlights>(_GetDirectFlights_QNAME, GetDirectFlights.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CBWSPublicUnauthorizedAccessException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "CBWSPublicUnauthorizedAccessException")
    public JAXBElement<CBWSPublicUnauthorizedAccessException> createCBWSPublicUnauthorizedAccessException(CBWSPublicUnauthorizedAccessException value) {
        return new JAXBElement<CBWSPublicUnauthorizedAccessException>(_CBWSPublicUnauthorizedAccessException_QNAME, CBWSPublicUnauthorizedAccessException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightLookup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.connections.oag.com/", name = "flightLookup")
    public JAXBElement<FlightLookup> createFlightLookup(FlightLookup value) {
        return new JAXBElement<FlightLookup>(_FlightLookup_QNAME, FlightLookup.class, null, value);
    }

}
