//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 12:38:47 PM IST 
//


package com.ibsplc.framework.util.sogl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CODE"/>
 *         &lt;element ref="{}LIST_VALUE" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "code",
    "listvalue"
})
@XmlRootElement(name = "LIST_ELEMENT")
public class LISTELEMENT {

    @XmlElement(name = "CODE")
    protected String code;
    @XmlElement(name = "LIST_VALUE", required = true)
    protected List<LISTVALUE> listvalue;

    /**
     * Gets the value of the code property.
     * 
     */
    public String getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCODE(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the listvalue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listvalue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLISTVALUE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LISTVALUE }
     * 
     * 
     */
    public List<LISTVALUE> getLISTVALUE() {
        if (listvalue == null) {
            listvalue = new ArrayList<LISTVALUE>();
        }
        return this.listvalue;
    }

}
