//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 12:38:47 PM IST 
//


package com.ibsplc.framework.util.sogl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.flysaa.framework.util.sogl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final  QName _NAME_QNAME = new QName("", "NAME");
    private static final  QName _CODE_QNAME = new QName("", "CODE");

    /**
     * Create a new ObjectFactory that can be used to 
     * create new instances of schema derived classes 
     * for package: com.flysaa.framework.util.sogl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SOGL }
     * 
     */
    public SOGL createSOGL() {
        return new SOGL();
    }

    /**
     * Create an instance of {@link GLOBALLIST }
     * 
     */
    public GLOBALLIST createGLOBALLIST() {
        return new GLOBALLIST();
    }

    /**
     * Create an instance of {@link LISTVALUE }
     * 
     */
    public LISTVALUE createLISTVALUE() {
        return new LISTVALUE();
    }

    /**
     * Create an instance of {@link LISTELEMENT }
     * 
     */
    public LISTELEMENT createLISTELEMENT() {
        return new LISTELEMENT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NAME")
    public JAXBElement<String> createNAME(String value) {
        return new JAXBElement<String>(_NAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CODE")
    public JAXBElement<Byte> createCODE(Byte value) {
        return new JAXBElement<Byte>(_CODE_QNAME, Byte.class, null, value);
    }

}
