package com.ibsplc.framework.util.sogl;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.05.12 at 12:38:47 PM IST 
//


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element ref="{}GLOBAL_LIST" maxOccurs="unbounded"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "globallist"
})
@XmlRootElement(name = "SO_GL")
public class SOGL {

 @XmlElement(name = "GLOBAL_LIST", required = true)
 protected List<GLOBALLIST> globallist;

 /**
  * Gets the value of the globallist property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the globallist property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getGLOBALLIST().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link GLOBALLIST }
  * 
  * 
  */
 public List<GLOBALLIST> getGLOBALLIST() {
     if (globallist == null) {
         globallist = new ArrayList<GLOBALLIST>();
     }
     return this.globallist;
 }

}
